parser: '@typescript-eslint/parser'
parserOptions:
  project: './tsconfig.json'

ignorePatterns:
  - 'build'

plugins:
  - '@typescript-eslint'
  - 'functional'

extends:
  - 'eslint:recommended'
  - 'standard-with-typescript'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:@typescript-eslint/recommended-requiring-type-checking'
  - 'plugin:functional/external-recommended'
  - 'plugin:functional/recommended'
  - 'plugin:functional/stylitic'
  - 'plugin:jest/all'

rules:
  '@typescript-eslint/promise-function-async': 'off'
  '@typescript-eslint/strict-boolean-expressions': 'off'
  '@typescript-eslint/explicit-function-return-type': 'off'
  '@typescript-eslint/consistent-type-assertions': 'off'
  '@typescript-eslint/explicit-module-boundary-types': 'off'
  '@typescript-eslint/consistent-type-definitions': ['error', 'type']
  'import/no-default-export': 'warn'
