parser: '@typescript-eslint/parser'
parserOptions:
  project: './tsconfig.json'

ignorePatterns:
  - 'build'

plugins:
  - '@typescript-eslint'
  - 'prettier'

extends:
  - 'eslint:recommended'
  - 'standard-with-typescript'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:@typescript-eslint/recommended-requiring-type-checking'
  - 'plugin:jest/all'
  - 'plugin:prettier/recommended'
